version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
  commands:
    - echo Build completed on `date`
    - aws deploy push \
      --application-name java-project-codedeploy \
      --s3-location s3://java-artifacts/java-project-build/LoginWebApp-1.war \
      --ignore-hidden-files

artifacts:
  files:
    - '**/LoginWebApp-1.war'
    - 'appspec.yml'
  discard-paths: yes
