version: 0.2
env:
  variables:
    S3_BUCKET: "java-artifacts"
phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3 rm s3://java-artifacts/java-project-build/LoginWebApp-1.war
      - aws s3 cp '/target/LoginWebApp-1.war' s3://java-artifacts/java-project-build

artifacts:
  files:
    - '**/LoginWebApp-1.war'
    - 'appspec.yml'
  discard-paths: yes
